### ISSUE TITLE
How use that with Meteor on client side?

### ISSUE THREAD

**Issue by jadsonlourenco** [udondan/googlefonts#2]
What this package do? In addition to making a call from the server side, it saves the fonts on the server to use on client side? And how do the call on the client side?

Thank you.

**Comment by udondan** [comment]
The package only loads the fonts on the server side. It's not directly possible on the client and would be a problem because it would make your API key publicly available. There are two ways how to deliver the font list to the client.

1. **Create a server side method which can be invoked from client side**
Create such a method with [`Meteor.methods`](http://docs.meteor.com/#/basic/Meteor-methods) and then call it from client with [`meteor.call`](http://docs.meteor.com/#/basic/Meteor-call). The server side method can fetch the fonts directly from the Google API and return it to the client.

2. **Store in collection**
Since the fonts do not change rapidly, you can set a interval on the server and permanently fetch the fonts every few hours, store it in a collection and then simply deliver the collection to the client.

The 2nd solution has several benefits:
 - You do not have to take care yourself of shipping the data to the client. Just subscribe to the collection.
 - Better user experience, since the client does not have to wait for the fonts to load from Google.
 - You can query the fonts collection and easily deliver only a subset w/o implementing own routines

In one of my projects ([localfont.com](http://www.localfont.com/)) I use this below snippet to load all fonts once per hour on the server and store it in the collection "Fontlist"

```js
// google fonts api key. if rejected, get new: https://console.developers.google.com/project/apps~local-fonts/apiui/credential
var serverKey = "your-google-key-here";
var gfonts = new googlefonts(serverKey);

// fetch font list from googleapi and save to fontlist collection
var loadFonts = function() {
  gfonts.fetch(Meteor.bindEnvironment(function(error, f) {
    if(typeof error !== "undefined") {
      Meteor.log.error(error);
      Meteor.http.get("http://curlmyip.com", {}, function(error, result) {
        Meteor.log.debug("Local IP: " + result.content.replace(/[^\w\d\.]/, ""));
      });
    }
    if(typeof f == "object" && typeof f.kind == "string" && f.kind == "webfonts#webfontList" && typeof f.items == "object" && Object.keys(f.items).length > 0) {
      bulkCollectionUpdate(Fontlist, f.items , {
        primaryKey: "family",
        deleteMissing: true,
        callback: function() {
          Meteor.log.debug("Fonts updated. Collection now has " + Fontlist.find().count() + " items.");
        }
      });
    }
  }, function () { console.log('Failed to bind environment'); }));
}

// load fonts from google api now!
loadFonts();

// as well every hour
setInterval(function() {
  loadFonts();
}, 60000 * 60);
```



The `Meteor.log` feature is provided through [mrt:trail](https://atmospherejs.com/mrt/trail) and the method `bulkCollectionUpdate` is another package of mine, [udondan:bulk-collection-update](https://atmospherejs.com/udondan/bulk-collection-update)

HTH

**Comment by jadsonlourenco** [comment]
Ok, thank you for your response was really amazing!

Yes, that's exactly what I was thinking in downloading the sources at server side and the client get those sources by the server, not the CDN/Google. Save in a collection was a great idea, I knew I needed to use a method, but the collection was better, because we can cache this collection on the client.

But now the only question I have is how I will use this value of the collection, usually when we use google fonts can add a tag in the "<head>" or "@font-face" to import sources. But how do you do that with the answer that has saved the font collection? I know how get this from collection, but don't know how do for the CSS/HTML can render templates with this fonts.

PS: I saw you app for fonts and is so good, thanks again.

**Comment by udondan** [comment]
This is a bit tricky. Because the API from google will only deliver the paths to the TTF files, but depending on the clients browser you will need different font formats. Google delivers 4 different font types but the only way I know how to get the paths to the other 3 types is to request the CSS file from google and fake the user agent. AFAIK there is no API endpoint to get the different formats directly.

The CSS file can be requested like this: `http://fonts.googleapis.com/css?family=$family:$variant` Both `$family` and `$variant` are keys delivered in the font objects you just downloaded with this library and have stored now in a collection. Make sure to `urlencode` the `$family` part, e.g. "Open Sans" will have to be "Open+Sans" when you submit the request, e.g.: `http://fonts.googleapis.com/css?family=Open+Sans:300`

As written above, depending on the user agent, this file will contain different CSS rules containing the paths to the actual font files. Here are the four types and the user agent strings you can use to get the required results:

 - **TTF**: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/534.54.16 (KHTML, like Gecko) Version/5.1.4 Safari/534.54.16
 - **WOFF**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.69 Safari/537.36
 - **SVG**: Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B334b Safari/531.21.10
 - **EOT**: Mozilla/5.0 (MSIE 9.0; Windows NT 6.1; Trident/5.0)

Now there are 3 options how you can implement the fonts on the client:
 1. Simply use the above CSS and inject it into the client code. A had recently seen a smart package for loading CSS dynamically into the client, but I can't remember the name. Alternatively you can just create a new `<style>` block with JS in the client and set the content to what you received from Google. 
 2. Parse the resulting CSS and extract the font paths. When you have the font paths you can either:
  1. Create your own CSS rules and use the paths to the font files on the Google CDN
  2. Download the font files and store them either base64 encoded in your collection or write them to disk in the public folder, so they can be served to the client directly.

As said, this topic is a bit tricky. :)

**Comment by jadsonlourenco** [comment]
Yes, I understand and I've tried everything you said, I really was thinking of a way to use the Google API sources of a more dynamic way, where I could have saved fonts sources directly into the app, without having to make an HTTP request on client. But so far the best option is to use the fonts in a "base64", so they are packaged as part of the app/js, but will make a small "weight" in the first access, this works for mobile applications to look more "native".

Yes, this package is doing a good job to have the necessary templates using "routes": https://github.com/numtel/meteor-publicsources

I'll close this topic, thank you for clarifying things and share this package. Now I'm out of ideas to make a correct implementation of what I said before, but I'll keep thinking about it and if I get a result I tell you.

Thank you!
